name: 'Railway PR Delete Action'
description: 'Deletes a PR environment on Railway.'
inputs:
  RAILWAY_API_TOKEN:  # railway token
    description: 'Railway API Token'
    required: true
  PROJECT_ID:
    description: 'The id of the project to create environments on. Can be found on Settings -> General page'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'